import psycopg2

from config import user, password, host, db_name


async def connect_db():
    try:
        connection = psycopg2.connect(
            host=host,
            user=user,
            password=password,
            database=db_name
        )

        connection.autocommit = True

        cursor = connection.cursor()

        cursor.execute(
        """CREATE TABLE IF NOT EXISTS users(
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_user TEXT, 
        surname TEXT, 
        tg_id TEXT NOT NULL, 
        chat_id TEXT NOT NULL
        );"""
        )

        cursor.execute(
            """CREATE TABLE IF NOT EXISTS admin_tg (
            id SERIAL PRIMARY KEY,
            user_id int NOT NULL UNIQUE,
            admin_status BOOLEAN NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );"""
        )

    except Exception as ex:
        print(ex)
    finally:
        if connection:
            cursor.close()
            connection.close()